name: Close stale issues

on:
  schedule:
    - cron: '0 4 * * *'

permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            This issue has been automatically marked as stale due to 21 days of inactivity.
            It will be closed in 9 days if no further activity occurs.
          close-issue-message: |
            Closing this issue due to 30 days of inactivity. Feel free to reopen if needed.
          days-before-stale: 21
          days-before-close: 9
          exempt-issue-labels: 'enhancement,important,keep-open'
          only-issue-labels: ''
